defaults:
    - override hydra/launcher: submitit_local

# environment
task: stack-cube
obs: rgb
num_envs: 16

# evaluation
checkpoint: ???
eval_episodes: 10
eval_freq: 50000

# OT-reward
ot_reward_shaping: true
context_num: 3
mask_k: 10
niter: 100
ot_epsilon: 0.01
sinkhorn_rew_scale: 1
auto_rew_scale_factor: 10
update_succ_buffer: true
render_device: 0
ot_planning_lambda: 1
decay_ratio: 0.8
lambda_min: 1e-4

# RND intrinsic reward (exploration)
use_rnd: true
rnd_coef: 1.0
rnd_scale_start: 0.1
rnd_scale_end: 0.01
rnd_decay_steps: 125000   # 对应默认 steps=500k / steps_per_update=4


# training
algorithm: ???
steps: 500000
batch_size: 256
steps_per_update: 4 # utd = steps_per_update / num_envs (in this implementation)
ot_reward_coef: 0.1
reward_coef: 0.1
value_coef: 0.1
consistency_coef: 20
rho: 0.5
lr: 3e-4
enc_lr_scale: 0.3
grad_clip_norm: 20
tau: 0.01
discount_denom: 5
discount_min: 0.95
discount_max: 0.995
discount_hardcoded: 0.0 # Overrides heuristic discount calculation
buffer_size: 1_000_000
exp_name: tdmpc2
data_dir: ???
seed_scheduler: true


# speedups
compile: false

# planning
mpc: true
iterations: 6
num_samples: 512
num_elites: 64
num_pi_trajs: 24
horizon: 3
min_std: 0.05
max_std: 2
temperature: 0.5

# actor
log_std_min: -10
log_std_max: 2
entropy_coef: 1e-4

# critic
num_bins: 101
vmin: -10
vmax: +10

# architecture
model_size: ???
num_enc_layers: 2
enc_dim: 256
num_channels: 32
mlp_dim: 512
latent_dim: 512
task_dim: 96
num_q: 5
dropout: 0.01
simnorm_dim: 8

# logging
wandb_project: ???
wandb_entity: ???
wandb_silent: true
disable_wandb: true
save_csv: true
save_freq: 100_000

# misc
save_video: false
save_agent: false
render_obs: false
seed: 1

# convenience
work_dir: ???
task_title: ???
multitask: ???
tasks: ???
obs_shape: ???
action_dim: ???
episode_length: ???
obs_shapes: ???
action_dims: ???
episode_lengths: ???
seed_steps: ???
bin_size: ???
action_penalty: ???
max_bc_steps: ???

# environments
maniskill:
    action_repeat: 2
    obs_keys: ["agent", "image"]
    max_episode_steps: 100
    sim_backend: gpu
    action_penalty: false
    max_bc_steps: 3e4 #30_000
    camera:
        image_size: 128 # 64, 128, 256

metaworld:
    action_repeat: 2
    max_episode_steps: 100
    render_mode: "rgb_array" # "human", "rgb_array"
    reward_mode: ???
    obs: ???
    action_penalty: false
    max_bc_steps: 2e4 #20_000
    camera:
        image_size: 224 # 64, 128, 256

robosuite:
    action_repeat: 1
    render_mode: "rgb_array" # "human", "rgb_array"
    obs: ???
    action_penalty: false
    max_bc_steps: 5e3 #50_000
    camera:
        image_size: 128 # 64, 128, 256
